version: '3.8'
services:
  database:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: collabeek
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    # ports:
    #   - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: "host"

  adminer:
    image: adminer
    restart: always
    # ports:
    #   - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: "localhost:5432"
    depends_on:
      - database
    network_mode: "host"
  
  fakesmtp:
    image: mailhog/mailhog:latest
    restart: always
    environment:
      MH_AUTH_FILE: /mailhog.auth
    volumes:
      - ./mailhog.auth:/mailhog.auth:ro
    # ports:
    #   - 1025:1025
    #   - 8025:8025
    network_mode: "host"

volumes:
  postgres-data:
