// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type Roles string

const (
	RolesAdmin     Roles = "admin"
	RolesModerator Roles = "moderator"
	RolesMember    Roles = "member"
)

func (e *Roles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Roles(s)
	case string:
		*e = Roles(s)
	default:
		return fmt.Errorf("unsupported scan type for Roles: %T", src)
	}
	return nil
}

type NullRoles struct {
	Roles Roles
	Valid bool // Valid is true if Roles is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoles) Scan(value interface{}) error {
	if value == nil {
		ns.Roles, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Roles.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoles) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Roles), nil
}

type Member struct {
	ID                 int32
	Username           string
	Fullname           string
	Password           string
	Email              string
	RegistrationSecret string
	EmailConfirmed     bool
	Role               Roles
	CreatedAt          time.Time
	UpdatedAt          sql.NullTime
}

type Team struct {
	ID          int32
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

type TeamMember struct {
	ID        int32
	MemberID  int32
	TeamID    int32
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}
